<template>
  <section v-if="instance" class="surface" v-loading="loading"><div class="toolbar"><div><h2>短链接</h2><p>公开地址使用平台固定的 <code>/s/{code}</code> 路径。</p></div><el-button v-if="canManage" type="primary" @click="openCreate">创建短链接</el-button></div><el-table :data="links"><el-table-column prop="code" label="短码" min-width="120" /><el-table-column prop="targetUrl" label="目标 URL" min-width="240" show-overflow-tooltip /><el-table-column prop="clickCount" label="点击" width="90" /><el-table-column label="状态" width="90"><template #default="{ row }"><el-tag :type="row.enabled ? 'success' : 'info'">{{ row.enabled ? '启用' : '停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="260" fixed="right"><template #default="{ row }"><el-button link @click="copy(row.publicUrl)">复制</el-button><el-button link @click="showStats(row)">统计</el-button><template v-if="canManage"><el-button link @click="edit(row)">编辑</el-button><el-button link :type="row.enabled ? 'warning' : 'primary'" @click="toggle(row)">{{ row.enabled ? '停用' : '启用' }}</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></template></el-table-column></el-table><el-empty v-if="!links.length && !loading" description="暂无短链接" />
    <el-dialog v-model="dialog" :title="editing ? '编辑短链接' : '创建短链接'" width="520px"><el-form label-position="top"><el-form-item label="目标 URL"><el-input v-model="form.targetUrl" /></el-form-item><el-form-item v-if="!editing" label="自定义短码（可选）"><el-input v-model="form.code" /></el-form-item><el-form-item label="过期时间（可选）"><el-date-picker v-model="form.expiresAt" type="datetime" style="width:100%" /></el-form-item></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
    <el-dialog v-model="statsDialog" title="短链统计" width="640px"><template v-if="stats"><p>总点击：<strong>{{ stats.totalClicks }}</strong></p><el-table :data="stats.clicksByDay"><el-table-column prop="date" label="日期" /><el-table-column prop="count" label="点击" /></el-table></template></el-dialog>
  </section>
</template>
<script setup lang="ts">
import { ref, watch } from 'vue'; import { ElMessage, ElMessageBox } from 'element-plus'; import type { DeveloperProductInstanceDto, DeveloperShortLinkDto, DeveloperShortLinkStatsDto } from '@/client/types.gen'; import { developerProductService } from '@/service/developerProductService'
const props=defineProps<{instance?:DeveloperProductInstanceDto;canManage:boolean}>(); const loading=ref(false); const links=ref<DeveloperShortLinkDto[]>([]); const dialog=ref(false); const editing=ref<DeveloperShortLinkDto>(); const statsDialog=ref(false); const stats=ref<DeveloperShortLinkStatsDto>(); const form=ref({targetUrl:'',code:'',expiresAt:null as Date|null}); const load=async()=>{if(!props.instance)return;loading.value=true;try{links.value=await developerProductService.listShortLinkResources(props.instance.id)}finally{loading.value=false}}; const openCreate=()=>{editing.value=undefined;form.value={targetUrl:'',code:'',expiresAt:null};dialog.value=true};const edit=(row:DeveloperShortLinkDto)=>{editing.value=row;form.value={targetUrl:row.targetUrl,code:'',expiresAt:row.expiresAt?new Date(row.expiresAt):null};dialog.value=true};const save=async()=>{if(!props.instance)return;const body={targetUrl:form.value.targetUrl,expiresAt:form.value.expiresAt?.toISOString()};if(editing.value)await developerProductService.updateShortLinkResource(props.instance.id,editing.value.id,body);else await developerProductService.createShortLinkResource(props.instance.id,{...body,code:form.value.code||undefined});dialog.value=false;await load();ElMessage.success('短链接已保存')};const toggle=async(row:DeveloperShortLinkDto)=>{if(!props.instance)return;await developerProductService.updateShortLinkResource(props.instance.id,row.id,{enabled:!row.enabled});await load()};const remove=async(row:DeveloperShortLinkDto)=>{if(!props.instance)return;await ElMessageBox.confirm(`删除短链接 ${row.code} 后无法恢复。`,'删除短链接',{type:'warning'});await developerProductService.deleteShortLinkResource(props.instance.id,row.id);await load();ElMessage.success('短链接已删除')};const copy=async(value:string)=>{await navigator.clipboard.writeText(value);ElMessage.success('已复制')};const showStats=async(row:DeveloperShortLinkDto)=>{if(!props.instance)return;stats.value=await developerProductService.shortLinkStats(props.instance.id,row.id);statsDialog.value=true};watch(()=>props.instance?.id,load,{immediate:true})
</script><style scoped>.toolbar{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:16px}.toolbar h2{margin:0 0 6px;font-size:17px}.toolbar p{margin:0;color:var(--el-text-color-secondary)}</style>
