<template>
  <section v-if="instance" class="resource-panel" v-loading="loading">
    <div class="toolbar"><div><h2>{{ t('productResources.shortLinkTitle') }}</h2><p>{{ t('productResources.shortLinkDescription') }}</p></div><el-button v-if="canManage" type="primary" @click="openCreate">{{ t('productResources.createShortLink') }}</el-button></div>
    <el-table :data="links"><el-table-column prop="code" :label="t('productResources.shortCode')" min-width="120"/><el-table-column prop="targetUrl" :label="t('productResources.targetUrl')" min-width="240" show-overflow-tooltip/><el-table-column prop="clickCount" :label="t('productResources.clicks')" width="90"/><el-table-column :label="t('productResources.status')" width="90"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?t('productResources.enabled'):t('productResources.disabled')}}</el-tag></template></el-table-column><el-table-column :label="t('productResources.actions')" width="260" fixed="right"><template #default="{row}"><el-button link @click="copy(row.publicUrl)">{{t('copy')}}</el-button><el-button link @click="showStats(row)">{{t('productResources.statistics')}}</el-button><template v-if="canManage"><el-button link @click="edit(row)">{{t('productResources.edit')}}</el-button><el-button link :type="row.enabled?'warning':'primary'" @click="toggle(row)">{{row.enabled?t('productResources.disabled'):t('productResources.enabled')}}</el-button><el-button link type="danger" @click="remove(row)">{{t('productResources.delete')}}</el-button></template></template></el-table-column></el-table><el-empty v-if="!links.length&&!loading" :description="t('productResources.empty')"/>
    <el-dialog v-model="dialog" :title="editing?t('productResources.edit'):t('productResources.createShortLink')" width="520px" destroy-on-close><el-form label-position="top"><el-form-item :label="t('productResources.targetUrl')"><el-input v-model="form.targetUrl"/></el-form-item><el-form-item v-if="!editing" :label="t('productResources.customShortCode')"><el-input v-model="form.code"/></el-form-item><el-form-item :label="t('productResources.expiresAt')"><el-date-picker v-model="form.expiresAt" type="datetime" style="width:100%"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">{{t('cancel')}}</el-button><el-button type="primary" @click="save">{{t('productResources.save')}}</el-button></template></el-dialog>
    <el-dialog v-model="statsDialog" :title="t('productResources.statistics')" width="640px"><template v-if="stats"><p>{{t('productResources.totalClicks')}}: <strong>{{stats.totalClicks}}</strong></p><el-table :data="stats.clicksByDay"><el-table-column prop="date" :label="t('productResources.date')"/><el-table-column prop="count" :label="t('productResources.clicks')"/></el-table></template></el-dialog>
  </section>
</template>
<script setup lang="ts">
import { ref, watch } from 'vue'; import { ElMessage, ElMessageBox } from 'element-plus'; import type { DeveloperProductInstanceDto, DeveloperShortLinkDto, DeveloperShortLinkStatsDto } from '@/client/types.gen'; import { developerProductService } from '@/service/developerProductService'; import { i18ns } from '@/locales'
const { t } = i18ns; const props=defineProps<{instance?:DeveloperProductInstanceDto;canManage:boolean}>(); const loading=ref(false); const links=ref<DeveloperShortLinkDto[]>([]); const dialog=ref(false); const editing=ref<DeveloperShortLinkDto>(); const statsDialog=ref(false); const stats=ref<DeveloperShortLinkStatsDto>(); const form=ref({targetUrl:'',code:'',expiresAt:null as Date|null}); const load=async()=>{if(!props.instance)return;loading.value=true;try{links.value=await developerProductService.listShortLinkResources(props.instance.id)}finally{loading.value=false}}; const openCreate=()=>{editing.value=undefined;form.value={targetUrl:'',code:'',expiresAt:null};dialog.value=true};const edit=(row:DeveloperShortLinkDto)=>{editing.value=row;form.value={targetUrl:row.targetUrl,code:'',expiresAt:row.expiresAt?new Date(row.expiresAt):null};dialog.value=true};const save=async()=>{if(!props.instance)return;const body={targetUrl:form.value.targetUrl,expiresAt:form.value.expiresAt?.toISOString()};if(editing.value)await developerProductService.updateShortLinkResource(props.instance.id,editing.value.id,body);else await developerProductService.createShortLinkResource(props.instance.id,{...body,code:form.value.code||undefined});dialog.value=false;await load();ElMessage.success(t('updateSuccess'))};const toggle=async(row:DeveloperShortLinkDto)=>{if(!props.instance)return;await developerProductService.updateShortLinkResource(props.instance.id,row.id,{enabled:!row.enabled});await load()};const remove=async(row:DeveloperShortLinkDto)=>{if(!props.instance)return;await ElMessageBox.confirm(`${t('delete')} ${row.code}?`,t('confirmDelete'),{type:'warning'});await developerProductService.deleteShortLinkResource(props.instance.id,row.id);await load();ElMessage.success(t('deleteSuccess'))};const copy=async(value:string)=>{await navigator.clipboard.writeText(value);ElMessage.success(t('copySuccess'))};const showStats=async(row:DeveloperShortLinkDto)=>{if(!props.instance)return;stats.value=await developerProductService.shortLinkStats(props.instance.id,row.id);statsDialog.value=true};watch(()=>props.instance?.id,load,{immediate:true})
</script><style scoped>.toolbar{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:16px}.toolbar h2{margin:0 0 6px;font-size:17px}.toolbar p{margin:0;color:var(--el-text-color-secondary)}</style>
