/**
 * 服务器配置项的 key 常量
 */

export const CONFIG_KEYS = {
  HEARTBEAT: {
    INTERVAL_SECONDS: "heartbeat.intervalSeconds",
    TIMEOUT_SECONDS: "heartbeat.timeoutSeconds",
  },
  DATA_LIFECYCLE: {
    SCHEDULE_ENABLED: "dataLifecycle.schedule.enabled",
    SCHEDULE_TIME: "dataLifecycle.schedule.time",
  },
  REMOTE_TERMINAL: {
    UNBIND_MAX_COUNT: "remoteTerminal.unbind.maxCount",
    UNBIND_WINDOW_HOURS: "remoteTerminal.unbind.windowHours",
    REBIND_COOLDOWN_MINUTES: "remoteTerminal.unbind.rebindCooldownMinutes",
  },
  BILLING: {
    RECHARGE_RATIO: "billing.rechargeRatio",
    GIFT_CODE_ENABLED: "billing.giftCodeEnabled",
    DIRECT_TRANSFER_ENABLED: "billing.directTransferEnabled",
    GIFT_CODE_FEE_PERCENT: "billing.giftCodeFeePercent",
    DIRECT_TRANSFER_FEE_PERCENT: "billing.directTransferFeePercent",
    GIFT_CODE_CANCEL_FEE_REFUND_PERCENT: "billing.giftCodeCancelFeeRefundPercent",
  },
  DEVELOPER: {
    VERIFICATION_OVERAGE_PRICE: "developer.pricing.verification",
    IP_OVERAGE_PRICE: "developer.pricing.ip",
    PUSH_OVERAGE_PRICE: "developer.pricing.push",
    SMS_ENDPOINT: "developer.sms.endpoint",
    SMS_TOKEN: "developer.sms.token",
    SMS_SENDER: "developer.sms.sender",
  },
  CAPTCHA: {
    PROVIDER: "captcha.provider",
    FALLBACK_PROVIDER: "captcha.fallbackProvider",
    MIN_SCORE: "captcha.minScore",
    TRUST_WINDOW_MINUTES: "captcha.trustWindowMinutes",
  },
  REGISTRATION: {
    ENABLED: "registration.enabled",
    MAX_ACCOUNTS_PER_EMAIL: "registration.maxAccountsPerEmail",
    DEFAULT_GROUP_USERNAME: "registration.defaultGroupUsername",
    VERIFICATION_CODE_EXPIRY: "registration.verificationCodeExpiry",
  },
  SMTP: {
    HOST: "smtp.host",
    PORT: "smtp.port",
    SECURE: "smtp.secure",
    USER: "smtp.user",
    PASSWORD: "smtp.password",
    SENDER_NAME: "smtp.senderName",
    SENDER_EMAIL: "smtp.senderEmail",
  },
  NOTIFICATION: {
    DEFAULT_SUBSCRIBED_EVENTS: "notification.defaultSubscribedEvents",
    DEFAULT_THRESHOLDS: "notification.defaultThresholds",
    TICKET_ASSIGNMENT_RULES: "notification.ticketAssignmentRules",
  },
  IP_BAN: {
    ENABLED: "ipBan.enabled",
    ERROR_WEIGHTS: "ipBan.errorWeights",
    LEVEL_1_THRESHOLD: "ipBan.level1Threshold",
    LEVEL_1_DURATION: "ipBan.level1Duration",
    LEVEL_2_THRESHOLD: "ipBan.level2Threshold",
    LEVEL_2_DURATION: "ipBan.level2Duration",
    LEVEL_3_THRESHOLD: "ipBan.level3Threshold",
    LEVEL_3_DURATION: "ipBan.level3Duration",
    ERROR_DECAY_ENABLED: "ipBan.errorDecayEnabled",
    ERROR_DECAY_RATE: "ipBan.errorDecayRate",
    ERROR_DECAY_MIN_THRESHOLD: "ipBan.errorDecayMinThreshold",
    ERROR_DECAY_INTERVAL: "ipBan.errorDecayInterval",
  },
  SITE: {
    BACKEND_PUBLIC_URL: "site.backendPublicUrl",
  },
  SUPPORT_AI: {
    ENABLED: "supportAi.enabled",
    UPSTREAM_URL: "supportAi.upstreamUrl",
    API_KEY: "supportAi.apiKey",
    MODEL: "supportAi.model",
    REQUEST_FORMAT: "supportAi.requestFormat",
    SYSTEM_PROMPT: "supportAi.systemPrompt",
    MAX_REQUESTS: "supportAi.maxRequests",
    WINDOW_SECONDS: "supportAi.windowSeconds",
    MAX_AGENT_ROUNDS: "supportAi.maxAgentRounds",
    MAX_OUTPUT_TOKENS: "supportAi.maxOutputTokens",
    ALLOW_USER_BALANCE: "supportAi.allowUserBalance",
    ALLOW_USER_RELAY_TOKEN: "supportAi.allowUserRelayToken",
    SESSION_RETENTION_DAYS: "supportAi.sessionRetentionDays",
    INPUT_PRICE_PER_MILLION: "supportAi.inputPricePerMillion",
    OUTPUT_PRICE_PER_MILLION: "supportAi.outputPricePerMillion",
  },
  SOCIAL_AUTH: {
    FRONTEND_BASE_URL: "socialAuth.frontendBaseUrl",
    QR_LOGIN_ENABLED: "socialAuth.qrLoginEnabled",
    STATE_TTL_SECONDS: "socialAuth.stateTtlSeconds",
    QR_LOGIN_TTL_SECONDS: "socialAuth.qrLoginTtlSeconds",
    QR_LOGIN_POLL_INTERVAL_SECONDS: "socialAuth.qrLoginPollIntervalSeconds",
    GITHUB: {
      ENABLED: "socialAuth.github.enabled",
      CLIENT_ID: "socialAuth.github.clientId",
      CLIENT_SECRET: "socialAuth.github.clientSecret",
      AUTHORIZE_URL: "socialAuth.github.authorizeUrl",
      TOKEN_URL: "socialAuth.github.tokenUrl",
      USER_URL: "socialAuth.github.userUrl",
      EMAIL_URL: "socialAuth.github.emailUrl",
      SCOPE: "socialAuth.github.scope",
      CALLBACK_PATH: "socialAuth.github.callbackPath",
    },
    WECHAT_OPEN: {
      ENABLED: "socialAuth.wechatOpen.enabled",
      APP_ID: "socialAuth.wechatOpen.appId",
      APP_SECRET: "socialAuth.wechatOpen.appSecret",
      AUTHORIZE_URL: "socialAuth.wechatOpen.authorizeUrl",
      TOKEN_URL: "socialAuth.wechatOpen.tokenUrl",
      USER_URL: "socialAuth.wechatOpen.userUrl",
      SCOPE: "socialAuth.wechatOpen.scope",
      CALLBACK_PATH: "socialAuth.wechatOpen.callbackPath",
    },
    WECHAT_WEB: {
      ENABLED: "socialAuth.wechatWeb.enabled",
      APP_ID: "socialAuth.wechatWeb.appId",
      APP_SECRET: "socialAuth.wechatWeb.appSecret",
      AUTHORIZE_URL: "socialAuth.wechatWeb.authorizeUrl",
      TOKEN_URL: "socialAuth.wechatWeb.tokenUrl",
      USER_URL: "socialAuth.wechatWeb.userUrl",
      SCOPE: "socialAuth.wechatWeb.scope",
      CALLBACK_PATH: "socialAuth.wechatWeb.callbackPath",
    },
  },
  RELAY: {
    UPSTREAM_URL: "relay.upstreamUrl",
    UPSTREAM_API_KEY: "relay.upstreamApiKey",
    OPENAI_UPSTREAM_URL: "relay.openaiUpstreamUrl",
    OPENAI_UPSTREAM_API_KEY: "relay.openaiUpstreamApiKey",
    ANTHROPIC_UPSTREAM_URL: "relay.anthropicUpstreamUrl",
    ANTHROPIC_UPSTREAM_API_KEY: "relay.anthropicUpstreamApiKey",
    ALLOWED_MODELS: "relay.allowedModels",
    MODEL_RATES: "relay.modelRates",
    GLOBAL_MULTIPLIER: "relay.globalMultiplier",
    CUSTOM_KEY_ENABLED: "relay.customKey.enabled",
    CUSTOM_KEY_MAX_TOKENS_PER_USER: "relay.customKey.maxTokensPerUser",
    CUSTOM_KEY_CREATE_LIMIT_WINDOW_MINUTES: "relay.customKey.createLimitWindowMinutes",
    CUSTOM_KEY_CREATE_LIMIT_MAX_COUNT: "relay.customKey.createLimitMaxCount",
    UPSTREAM_PROXY_ENABLED: "relay.upstreamProxy.enabled",
    UPSTREAM_PROXY_URL: "relay.upstreamProxy.url",
  },
  CONTENT_SAFETY: {
    REQUEST_ENABLED: "security.contentSafety.request.enabled",
    REQUEST_ACTION: "security.contentSafety.request.action",
    REQUEST_MAX_ACTION: "security.contentSafety.request.maxAction",
    REQUEST_AI_ENABLED: "security.contentSafety.request.aiEnabled",
    REQUEST_AI_ACTION: "security.contentSafety.request.aiAction",
    RESPONSE_ENABLED: "security.contentSafety.response.enabled",
    RESPONSE_ACTION: "security.contentSafety.response.action",
    RESPONSE_MAX_ACTION: "security.contentSafety.response.maxAction",
    RESPONSE_AI_ENABLED: "security.contentSafety.response.aiEnabled",
    RESPONSE_AI_ACTION: "security.contentSafety.response.aiAction",
    AI_UPSTREAM_URL: "security.contentSafety.ai.upstreamUrl",
    AI_API_KEY: "security.contentSafety.ai.apiKey",
    AI_MODEL: "security.contentSafety.ai.model",
    AI_REQUEST_FORMAT: "security.contentSafety.ai.requestFormat",
    AI_TIMEOUT_MS: "security.contentSafety.ai.timeoutMs",
    AI_INPUT_PRICE_PER_MILLION: "security.contentSafety.ai.inputPricePerMillion",
    AI_OUTPUT_PRICE_PER_MILLION: "security.contentSafety.ai.outputPricePerMillion",
    AI_MAX_TEXT_LENGTH: "security.contentSafety.ai.maxTextLength",
  },
} as const;
