/**
 * Business operation types for audit logging
 */
export enum OperationType {
  // Authentication
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILED = "LOGIN_FAILED",
  LOGOUT = "LOGOUT",
  TOKEN_REFRESH = "TOKEN_REFRESH",
  PASSWORD_CHANGE = "PASSWORD_CHANGE",
  ACCESS_KEY_CREATE = "ACCESS_KEY_CREATE",
  ACCESS_KEY_DELETE = "ACCESS_KEY_DELETE",
  OAUTH_CLIENT_CREATE = "OAUTH_CLIENT_CREATE",
  OAUTH_CLIENT_UPDATE = "OAUTH_CLIENT_UPDATE",
  OAUTH_CLIENT_DELETE = "OAUTH_CLIENT_DELETE",
  OAUTH_CLIENT_SECRET_ROTATE = "OAUTH_CLIENT_SECRET_ROTATE",
  OAUTH_CLIENT_SUBMIT_REVIEW = "OAUTH_CLIENT_SUBMIT_REVIEW",
  OAUTH_CLIENT_REVIEW_APPROVE = "OAUTH_CLIENT_REVIEW_APPROVE",
  OAUTH_CLIENT_REVIEW_REJECT = "OAUTH_CLIENT_REVIEW_REJECT",
  AUTH_CENTER_CLIENT_CREATE = "AUTH_CENTER_CLIENT_CREATE",
  AUTH_CENTER_CLIENT_UPDATE = "AUTH_CENTER_CLIENT_UPDATE",
  AUTH_CENTER_CLIENT_DELETE = "AUTH_CENTER_CLIENT_DELETE",
  AUTH_CENTER_CLIENT_SECRET_ROTATE = "AUTH_CENTER_CLIENT_SECRET_ROTATE",
  AUTH_CENTER_CLIENT_SUBMIT_REVIEW = "AUTH_CENTER_CLIENT_SUBMIT_REVIEW",
  AUTH_CENTER_CLIENT_REVIEW_APPROVE = "AUTH_CENTER_CLIENT_REVIEW_APPROVE",
  AUTH_CENTER_CLIENT_REVIEW_REJECT = "AUTH_CENTER_CLIENT_REVIEW_REJECT",
  AUTH_CENTER_TOKEN_ISSUE = "AUTH_CENTER_TOKEN_ISSUE",
  AUTH_CENTER_TOKEN_REFRESH = "AUTH_CENTER_TOKEN_REFRESH",
  AUTH_CENTER_TOKEN_REVOKE = "AUTH_CENTER_TOKEN_REVOKE",
  TWO_FACTOR_SETUP_BEGIN = "TWO_FACTOR_SETUP_BEGIN",
  TWO_FACTOR_SETUP_CONFIRM = "TWO_FACTOR_SETUP_CONFIRM",
  TWO_FACTOR_DISABLE = "TWO_FACTOR_DISABLE",
  TWO_FACTOR_PASSKEY_POLICY_UPDATE = "TWO_FACTOR_PASSKEY_POLICY_UPDATE",
  TWO_FACTOR_EMAIL_CODE_SEND = "TWO_FACTOR_EMAIL_CODE_SEND",
  TWO_FACTOR_RECOVERY_CODES_REGENERATE = "TWO_FACTOR_RECOVERY_CODES_REGENERATE",
  TWO_FACTOR_TRUSTED_DEVICE_VERIFY = "TWO_FACTOR_TRUSTED_DEVICE_VERIFY",
  TWO_FACTOR_TRUSTED_DEVICE_CREATE = "TWO_FACTOR_TRUSTED_DEVICE_CREATE",
  TWO_FACTOR_TRUSTED_DEVICE_DELETE = "TWO_FACTOR_TRUSTED_DEVICE_DELETE",
  EXTERNAL_AUTH_LOGIN = "EXTERNAL_AUTH_LOGIN",
  EXTERNAL_AUTH_BIND = "EXTERNAL_AUTH_BIND",
  EXTERNAL_AUTH_UNBIND = "EXTERNAL_AUTH_UNBIND",
  QR_LOGIN_CREATE = "QR_LOGIN_CREATE",
  QR_LOGIN_SCAN = "QR_LOGIN_SCAN",
  QR_LOGIN_CONFIRM = "QR_LOGIN_CONFIRM",

  // User Management
  USER_CREATE = "USER_CREATE",
  USER_UPDATE = "USER_UPDATE",
  USER_DELETE = "USER_DELETE",
  USER_STATUS_CHANGE = "USER_STATUS_CHANGE",
  USER_PROFILE_UPDATE = "USER_PROFILE_UPDATE",
  USER_EMAIL_CHANGE = "USER_EMAIL_CHANGE",
  USER_ONLINE_SESSION_START = "USER_ONLINE_SESSION_START",
  USER_ONLINE_SESSION_END = "USER_ONLINE_SESSION_END",
  USER_ONLINE_SESSION_IP_CHANGE = "USER_ONLINE_SESSION_IP_CHANGE",

  // Impersonation
  IMPERSONATION_START = "IMPERSONATION_START",

  // Permission Management
  PERMISSION_GRANT = "PERMISSION_GRANT",
  PERMISSION_REVOKE = "PERMISSION_REVOKE",
  PERMISSION_CLEAR = "PERMISSION_CLEAR",
  GROUP_PERMISSION_UPDATE = "GROUP_PERMISSION_UPDATE",

  // Group Management
  GROUP_CREATE = "GROUP_CREATE",
  GROUP_UPDATE = "GROUP_UPDATE",
  GROUP_DELETE = "GROUP_DELETE",
  USER_GROUP_CHANGE = "USER_GROUP_CHANGE",

  // System Operations
  SYSTEM_CONFIG_UPDATE = "SYSTEM_CONFIG_UPDATE",

  // Relay Operations
  RELAY_CHANNEL_CREATE = "RELAY_CHANNEL_CREATE",
  RELAY_CHANNEL_UPDATE = "RELAY_CHANNEL_UPDATE",
  RELAY_CHANNEL_STATUS_CHANGE = "RELAY_CHANNEL_STATUS_CHANGE",
  RELAY_CHANNEL_BATCH_STATUS_CHANGE = "RELAY_CHANNEL_BATCH_STATUS_CHANGE",
  RELAY_CHANNEL_DELETE = "RELAY_CHANNEL_DELETE",
  RELAY_CHANNEL_BATCH_DELETE = "RELAY_CHANNEL_BATCH_DELETE",
  RELAY_CHANNEL_DUPLICATE = "RELAY_CHANNEL_DUPLICATE",
  RELAY_CHANNEL_BATCH_DUPLICATE = "RELAY_CHANNEL_BATCH_DUPLICATE",
  RELAY_CHANNEL_BATCH_UPDATE = "RELAY_CHANNEL_BATCH_UPDATE",
  RELAY_CHANNEL_EXPORT = "RELAY_CHANNEL_EXPORT",
  RELAY_CHANNEL_IMPORT = "RELAY_CHANNEL_IMPORT",
  RELAY_CONFIG_UPDATE = "RELAY_CONFIG_UPDATE",
  MODEL_PRICING_CREATE = "MODEL_PRICING_CREATE",
  MODEL_PRICING_UPDATE = "MODEL_PRICING_UPDATE",
  MODEL_PRICING_DELETE = "MODEL_PRICING_DELETE",
  MODEL_PRICING_IMPORT = "MODEL_PRICING_IMPORT",
  RELAY_TOKEN_CREATE = "RELAY_TOKEN_CREATE",
  RELAY_TOKEN_REFRESH = "RELAY_TOKEN_REFRESH",
  RELAY_TOKEN_UPDATE = "RELAY_TOKEN_UPDATE",
  RELAY_TOKEN_CHANNEL_UPDATE = "RELAY_TOKEN_CHANNEL_UPDATE",
  RELAY_TOKEN_STATUS_CHANGE = "RELAY_TOKEN_STATUS_CHANGE",
  RELAY_TOKEN_BATCH_STATUS_CHANGE = "RELAY_TOKEN_BATCH_STATUS_CHANGE",
  RELAY_TOKEN_DELETE = "RELAY_TOKEN_DELETE",
  RELAY_TOKEN_BATCH_DELETE = "RELAY_TOKEN_BATCH_DELETE",
  RELAY_TOKEN_DUPLICATE = "RELAY_TOKEN_DUPLICATE",
  RELAY_TOKEN_BATCH_DUPLICATE = "RELAY_TOKEN_BATCH_DUPLICATE",
  RELAY_TOKEN_EXPORT = "RELAY_TOKEN_EXPORT",
  RELAY_TOKEN_IMPORT = "RELAY_TOKEN_IMPORT",
  RELAY_PROXY_REQUEST_SUCCESS = "RELAY_PROXY_REQUEST_SUCCESS",
  RELAY_PROXY_REQUEST_FAILED = "RELAY_PROXY_REQUEST_FAILED",

  // Billing Operations
  MONTHLY_PASS_TEMPLATE_CREATE = "MONTHLY_PASS_TEMPLATE_CREATE",
  MONTHLY_PASS_TEMPLATE_UPDATE = "MONTHLY_PASS_TEMPLATE_UPDATE",
  MONTHLY_PASS_TEMPLATE_DELETE = "MONTHLY_PASS_TEMPLATE_DELETE",
  MONTHLY_PASS_TEMPLATE_PUBLISH = "MONTHLY_PASS_TEMPLATE_PUBLISH",
  MONTHLY_PASS_TEMPLATE_UNPUBLISH = "MONTHLY_PASS_TEMPLATE_UNPUBLISH",
  MONTHLY_PASS_ASSIGNMENT_CREATE = "MONTHLY_PASS_ASSIGNMENT_CREATE",
  MONTHLY_PASS_ASSIGNMENT_UPDATE = "MONTHLY_PASS_ASSIGNMENT_UPDATE",
  MONTHLY_PASS_ASSIGNMENT_DELETE = "MONTHLY_PASS_ASSIGNMENT_DELETE",
  MONTHLY_PASS_SELF_CLAIM = "MONTHLY_PASS_SELF_CLAIM",
  REMOTE_TERMINAL_PRODUCT_TEMPLATE_CREATE = "REMOTE_TERMINAL_PRODUCT_TEMPLATE_CREATE",
  REMOTE_TERMINAL_PRODUCT_TEMPLATE_UPDATE = "REMOTE_TERMINAL_PRODUCT_TEMPLATE_UPDATE",
  REMOTE_TERMINAL_PRODUCT_TEMPLATE_DELETE = "REMOTE_TERMINAL_PRODUCT_TEMPLATE_DELETE",
  REMOTE_TERMINAL_PRODUCT_TEMPLATE_PUBLISH = "REMOTE_TERMINAL_PRODUCT_TEMPLATE_PUBLISH",
  REMOTE_TERMINAL_PRODUCT_TEMPLATE_UNPUBLISH = "REMOTE_TERMINAL_PRODUCT_TEMPLATE_UNPUBLISH",
  REMOTE_TERMINAL_ASSIGNMENT_CREATE = "REMOTE_TERMINAL_ASSIGNMENT_CREATE",
  REMOTE_TERMINAL_ASSIGNMENT_UPDATE = "REMOTE_TERMINAL_ASSIGNMENT_UPDATE",
  REMOTE_TERMINAL_ASSIGNMENT_DELETE = "REMOTE_TERMINAL_ASSIGNMENT_DELETE",
  REMOTE_TERMINAL_ASSIGNMENT_SELF_CLAIM = "REMOTE_TERMINAL_ASSIGNMENT_SELF_CLAIM",
  REMOTE_TERMINAL_REGISTRATION_TOKEN_ROTATE = "REMOTE_TERMINAL_REGISTRATION_TOKEN_ROTATE",
  REMOTE_TERMINAL_DEVICE_REVOKE = "REMOTE_TERMINAL_DEVICE_REVOKE",
  TICKET_CREATE = "TICKET_CREATE",
  TICKET_UPDATE = "TICKET_UPDATE",
  TICKET_COMMENT_CREATE = "TICKET_COMMENT_CREATE",
  TICKET_ASSIGN = "TICKET_ASSIGN",
  TICKET_TYPE_CHANGE = "TICKET_TYPE_CHANGE",
  TICKET_STATUS_CHANGE = "TICKET_STATUS_CHANGE",
  TICKET_PRIORITY_CHANGE = "TICKET_PRIORITY_CHANGE",
  TICKET_DELETE = "TICKET_DELETE",
  REDEMPTION_CODE_CREATE = "REDEMPTION_CODE_CREATE",
  REDEMPTION_CODE_DELETE = "REDEMPTION_CODE_DELETE",
  REDEMPTION_CODE_REDEEM = "REDEMPTION_CODE_REDEEM",
  BALANCE_GIFT_CODE_CREATE = "BALANCE_GIFT_CODE_CREATE",
  BALANCE_GIFT_CODE_CANCEL = "BALANCE_GIFT_CODE_CANCEL",
  BALANCE_GIFT_CODE_REDEEM = "BALANCE_GIFT_CODE_REDEEM",
  BALANCE_TRANSFER_CREATE = "BALANCE_TRANSFER_CREATE",

  // OJ Submitter Operations
  OJ_APIKEY_CREATE = "OJ_APIKEY_CREATE",
  OJ_APIKEY_UPDATE = "OJ_APIKEY_UPDATE",
  OJ_APIKEY_DELETE = "OJ_APIKEY_DELETE",
  OJ_PRICING_CREATE = "OJ_PRICING_CREATE",
  OJ_PRICING_UPDATE = "OJ_PRICING_UPDATE",
  OJ_PRICING_DELETE = "OJ_PRICING_DELETE",

  // Security Operations
  IP_BAN = "IP_BAN",
  IP_UNBAN = "IP_UNBAN",
  IP_WHITELIST_ADD = "IP_WHITELIST_ADD",
  IP_WHITELIST_REMOVE = "IP_WHITELIST_REMOVE",

  // JSON Endpoint Operations
  JSON_ENDPOINT_CREATE = "JSON_ENDPOINT_CREATE",
  JSON_ENDPOINT_UPDATE = "JSON_ENDPOINT_UPDATE",
  JSON_ENDPOINT_DELETE = "JSON_ENDPOINT_DELETE",
  JSON_ENDPOINT_KEY_REGENERATE = "JSON_ENDPOINT_KEY_REGENERATE",

  // Article Operations
  ARTICLE_CREATE = "ARTICLE_CREATE",
  ARTICLE_UPDATE = "ARTICLE_UPDATE",
  ARTICLE_DELETE = "ARTICLE_DELETE",
  ARTICLE_PUBLISH = "ARTICLE_PUBLISH",
  ARTICLE_UNPUBLISH = "ARTICLE_UNPUBLISH",

  // Legal Policy Operations
  LEGAL_POLICY_CREATE = "LEGAL_POLICY_CREATE",
  LEGAL_POLICY_UPDATE = "LEGAL_POLICY_UPDATE",
  LEGAL_POLICY_DELETE = "LEGAL_POLICY_DELETE",
  LEGAL_POLICY_PUBLISH = "LEGAL_POLICY_PUBLISH",
  LEGAL_POLICY_UNPUBLISH = "LEGAL_POLICY_UNPUBLISH",
  LEGAL_POLICY_ACCEPT = "LEGAL_POLICY_ACCEPT",

  // Notification Operations
  NOTIFICATION_PREFERENCE_UPDATE = "NOTIFICATION_PREFERENCE_UPDATE",
  NOTIFICATION_WEBHOOK_CREATE = "NOTIFICATION_WEBHOOK_CREATE",
  NOTIFICATION_WEBHOOK_UPDATE = "NOTIFICATION_WEBHOOK_UPDATE",
  NOTIFICATION_WEBHOOK_DELETE = "NOTIFICATION_WEBHOOK_DELETE",
}

/**
 * High-level categories for grouping operations
 */
export enum OperationCategory {
  AUTH = "AUTH",
  USER_MANAGEMENT = "USER_MANAGEMENT",
  PERMISSION = "PERMISSION",
  GROUP_MANAGEMENT = "GROUP_MANAGEMENT",
  SYSTEM = "SYSTEM",
  RELAY = "RELAY",
  BILLING = "BILLING",
  OJ_SUBMITTER = "OJ_SUBMITTER",
  SECURITY = "SECURITY",
  JSON_ENDPOINT = "JSON_ENDPOINT",
  ARTICLE = "ARTICLE",
  LEGAL_POLICY = "LEGAL_POLICY",
  NOTIFICATION = "NOTIFICATION",
}

export const ALL_OPERATION_TYPES = Object.values(OperationType) as OperationType[];

export const ALL_OPERATION_CATEGORIES = Object.values(OperationCategory) as OperationCategory[];
