import {
  Bell,
  ChatDotRound,
  Collection,
  Connection,
  Cpu,
  CreditCard,
  DataAnalysis,
  Document,
  FolderOpened,
  HomeFilled,
  Histogram,
  Key,
  Link,
  Lock,
  Monitor,
  Notebook,
  Operation,
  Postcard,
  Setting,
  Tools,
  TrendCharts,
  User,
  UserFilled,
  Wallet,
} from '@element-plus/icons-vue'
import type { Component } from 'vue'

// UI-only registry. Metadata references its key type without importing icon components.
const navigationIcons = {
  Bell,
  ChatDotRound,
  Collection,
  Connection,
  Cpu,
  CreditCard,
  DataAnalysis,
  Document,
  FolderOpened,
  HomeFilled,
  Histogram,
  Key,
  Link,
  Lock,
  Monitor,
  Notebook,
  Operation,
  Postcard,
  Setting,
  Tools,
  TrendCharts,
  User,
  UserFilled,
  Wallet,
} as const
export type NavigationIcon = keyof typeof navigationIcons
export const resolveNavigationIcon = (icon: NavigationIcon): Component => navigationIcons[icon]
