/**
 * 业务自定义状态码
 */
export enum CustomCode {
  OK = 0, // 操作成功
  AUTH_FAILED = 1001, // 认证失败
  VALIDATION_FAILED = 1002, // 参数校验失败
  NOT_FOUND = 1003, // 资源不存在
  PERMISSION_DENIED = 1004, // 权限不足
  INTERNAL_SERVER_ERROR = 1005, // 服务器内部错误
  TOKEN_EXPIRED_DUE_TO_UPDATE = 1006, // Token因用户信息变更而过期
  ACCOUNT_DISABLED = 1007, // 账号被禁用
  REGISTRATION_DISABLED = 1008, // 注册功能未开启
  EMAIL_LIMIT_REACHED = 1009, // 邮箱注册数量已达上限
  VERIFICATION_CODE_INVALID = 1010, // 验证码无效或已过期
  SMTP_NOT_CONFIGURED = 1011, // SMTP 未配置
  IP_BLACKLISTED = 1012, // IP 地址已被封禁
  TOKEN_EXPIRED = 1013, // Token 过期
  TOKEN_INVALID = 1014, // Token 无效/伪造
  LOGIN_AUTH_FAILED = 1015, // 登录认证失败（用户名或密码错误）
  TOO_MANY_REQUESTS = 1429, // 请求过于频繁
  REQUIRE_REPLAY_PROTECTION = 1016, // 需要启用重放保护
  REPLAY_PROTECTION_FAILED = 1017, // 重放保护失败
  TWO_FACTOR_REQUIRED = 1018, // 需要二次验证
  TWO_FACTOR_CHALLENGE_EXPIRED = 1019, // 二次验证会话已过期
  TWO_FACTOR_CODE_INVALID = 1020, // 二次验证码错误
  TWO_FACTOR_SETUP_SESSION_EXPIRED = 1021, // 二次验证配置会话已过期
  TWO_FACTOR_NOT_ENABLED = 1022, // 二次验证未开启
  TWO_FACTOR_ALREADY_ENABLED = 1023, // 二次验证已开启
  DISTRIBUTED_LOCK_CONFLICT = 1024, // 分布式锁冲突
  DISTRIBUTED_LOCK_BACKEND_UNAVAILABLE = 1025, // 分布式锁后端不可用
  IMPERSONATION_READONLY_VIOLATION = 1026, // 只读模拟模式下不允许写操作
  IMPERSONATION_NOT_ALLOWED = 1027, // 不允许模拟该用户
  POLICY_CONSENT_REQUIRED = 1028, // 需要重新同意最新服务协议与隐私政策
  LEGAL_POLICY_VERSION_CONFLICT = 1029, // 法律协议版本创建冲突
  RESOURCE_ALREADY_EXISTS = 1030, // 资源已存在/唯一约束冲突
  CAPTCHA_TRUST_REQUIRED = 1031, // 需要先建立人机验证信任 Cookie
  EXTERNAL_IDENTITY_ALREADY_BOUND = 1032, // 外部身份已绑定到其他账号
  EXTERNAL_IDENTITY_NOT_BOUND = 1033, // 外部身份尚未绑定
  EXTERNAL_AUTH_STATE_INVALID = 1034, // 外部登录 state 无效或已过期
  EXTERNAL_AUTH_PROVIDER_DISABLED = 1035, // 外部登录提供方未启用
  EXTERNAL_AUTH_BINDING_REQUIRED = 1036, // 外部身份未绑定，需要用户手动绑定
  EXTERNAL_AUTH_CALLBACK_INVALID = 1037, // 外部登录回调参数无效
  QR_LOGIN_SESSION_EXPIRED = 1038, // 扫码登录会话已过期
  QR_LOGIN_SESSION_CONSUMED = 1039, // 扫码登录会话已被处理
  QR_LOGIN_SESSION_PENDING = 1040, // 扫码登录尚未完成
}
