<template>
  <section v-if="instance" class="resource-panel" v-loading="loading"><div class="toolbar"><div><h2>{{t('productResources.secretTitle')}}</h2><p>{{t('productResources.secretDescription')}}</p></div><el-button v-if="canManage" type="primary" @click="openCreate">{{t('productResources.writeSecret')}}</el-button></div><el-table :data="secrets"><el-table-column prop="alias" :label="t('productResources.key')" min-width="200"><template #default="{row}"><code>{{row.alias}}</code></template></el-table-column><el-table-column prop="keyVersion" :label="t('productResources.version')" width="90"/><el-table-column :label="t('productResources.lastUsed')" min-width="170"><template #default="{row}">{{row.lastUsedAt?new Date(row.lastUsedAt).toLocaleString():t('productResources.neverUsed')}}</template></el-table-column><el-table-column v-if="canManage" :label="t('productResources.actions')" width="150"><template #default="{row}"><el-button link @click="rotate(row.alias)">{{t('productResources.rotate')}}</el-button><el-button link type="danger" @click="remove(row.alias)">{{t('productResources.delete')}}</el-button></template></el-table-column></el-table><el-empty v-if="!secrets.length&&!loading" :description="t('productResources.empty')"/>
    <el-dialog v-model="dialog" :title="rotating?t('productResources.rotate'):t('productResources.writeSecret')" width="500px" destroy-on-close><el-form label-position="top"><el-form-item :label="t('productResources.key')"><el-input v-model="form.alias" :disabled="rotating"/></el-form-item><el-form-item :label="t('productResources.secretValue')"><el-input v-model="form.value" type="password" show-password/></el-form-item></el-form><template #footer><el-button @click="dialog=false">{{t('cancel')}}</el-button><el-button type="primary" @click="save">{{t('productResources.save')}}</el-button></template></el-dialog>
  </section>
</template>
<script setup lang="ts">
import { ref, watch } from 'vue'; import { ElMessage, ElMessageBox } from 'element-plus'; import type { DeveloperProductInstanceDto, DeveloperSecretDto } from '@/client/types.gen'; import { developerProductService } from '@/service/developerProductService'; import { i18ns } from '@/locales'
const { t }=i18ns; const props=defineProps<{instance?:DeveloperProductInstanceDto;canManage:boolean}>(); const loading=ref(false),secrets=ref<DeveloperSecretDto[]>([]),dialog=ref(false),rotating=ref(false),form=ref({alias:'',value:''}); const load=async()=>{if(!props.instance)return;loading.value=true;try{secrets.value=await developerProductService.listSecretResources(props.instance.id)}finally{loading.value=false}}; const openCreate=()=>{rotating.value=false;form.value={alias:'',value:''};dialog.value=true};const rotate=(alias:string)=>{rotating.value=true;form.value={alias,value:''};dialog.value=true};const save=async()=>{if(!props.instance)return;await developerProductService.upsertSecretResource(props.instance.id,form.value);dialog.value=false;await load();ElMessage.success(t('updateSuccess'))};const remove=async(alias:string)=>{if(!props.instance)return;await ElMessageBox.confirm(`${t('delete')} ${alias}?`,t('confirmDelete'),{type:'warning'});await developerProductService.deleteSecretResource(props.instance.id,alias);await load();ElMessage.success(t('deleteSuccess'))};watch(()=>props.instance?.id,load,{immediate:true})
</script><style scoped>.toolbar{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:16px}.toolbar h2{margin:0 0 6px;font-size:17px}.toolbar p{margin:0;color:var(--el-text-color-secondary)}</style>
